Implement single end reads as an option and add output information about percent uniqueness.

diff --git a/src/PreProcessR b/src/PreProcessR
--- a/src/PreProcessR
+++ b/src/PreProcessR
@@ -9,6 +9,7 @@ readsize=150
 outdir='StrainR2DB'
 excludesize=10000
 memory_efficient=""
+singleend=false
 
 #parse options
 i=0
@@ -22,6 +23,7 @@ for argument in $options
       -r | --readsize) readsize="${arguments[i]}" ;;
       -s | --subcontigsize) subcontigsize="${arguments[i]}" ;;
       -e | --excludesize) excludesize="${arguments[i]}" ;;
+      -m | --singleend) singleend=true ;;
 #      -m | --memoryefficient) memory_efficient="-m" ;;
       -h | --help) 
             printf "USAGE: PreProcessR -i path/to/in [OPTIONS]\n\
@@ -32,7 +34,8 @@ PreProcessR counts the unique hashes in subcontigs for StrainR to normalize read
 \t\t-o/--outdir path/to/out\t\t: path to your output directory [Default = StrainR2DB]\n\
 \t\t-e/--excludesize number\t\t: exclude subcontig size (minimum subcontig size) [Default = 10000]\n\
 \t\t-s/--subcontigsize number\t: maximum subcontig size (overrides default use of calculated smallest N50)[Default = N50]\n\
-\t\t-r/--readsize number\t\t: Size of one end of a read. E.g.: for 150bp paired end reads readsize is 150. All reads must be paired. [Default = 150]\n\
+\t\t-r/--readsize number\t\t: Size of one end of a read. e.g.: for 150bp paired end reads readsize is 150. [Default = 150]\n\
+\t\t-m/--singleend\t\t\t: Flag that should be used if only single end reads will be provided to StrainR2. Disabled by default.\n\
 \t\t-h/--help\t\t\t: Display this message\n"
             exit
             ;;
@@ -43,30 +46,46 @@ if [ -z "$indir" ]; then
   echo "Error: Input directory needs to be specified with -i or --indir. Use 'PreprocessR --help' for more info."
   exit
 fi
-  
+if [ ! -d "$indir" ]; then
+  echo "Error: Input directory doesn't exist."
+  exit
+fi
 
 #preprocessr pipeline
 echo "Creating subcontigs"
-mkdir "$outdir"
-ksize=$(($readsize * 2 + 1))
+if ! mkdir "$outdir"; then
+  echo "Error: failed to create outdir. Exiting."
+  exit
+fi
+
+if [[ $singleend == true ]]; then
+  echo "WARNING: you have enabled single ended reads"
+  # makes kmer size odd if the read size isn't odd
+  ksize=$(($readsize / 2 * 2 + 1))
+else
+  ksize=$(($readsize * 2 + 1))
+fi
 
 if ! [ -z "$subcontigsize" ]; then
-  subcontigsize="-s $subcontigsize"
+  subcontigsize_opt="-s $subcontigsize"
 fi
 
 
-if ! subcontig -i "$indir" -o "$outdir" -e "$excludesize" "$subcontigsize"; then
+if ! subcontig -i "$indir" -o "$outdir" -e "$excludesize" "$subcontigsize_opt"; then
   echo "Subcontig generation failed"
   exit
 fi
 
+# number of subcontigs based on number of subcontig files written
 num_subconts=$(printf "$(ls -l "$outdir"/Subcontigs/ | wc -l)+$(ls -l "$outdir"/excludedSubcontigs/ | wc -l)\n" | bc)
 if ! hashcounter -s "$outdir"/Subcontigs/ -e "$outdir"/excludedSubcontigs/ -k "$ksize" -o "$outdir" -n "$num_subconts"; then
   echo "Hashing failed"
   exit
 fi
 
+# filter excluded subcontigs from KmerContent.report
 sed -i -n -E '/;EXCLUDED_.+\tEXCLUDED_/!p' "$outdir"/KmerContent.report
+
 echo "Generating BBIndex"
 mkdir "$outdir"/BBindex
 ls "$outdir"/Subcontigs/ | sed -n '/\.subcontig$/p' | sed 's|^|'"$outdir"'/Subcontigs/|' | \
@@ -74,6 +93,26 @@ ls "$outdir"/Subcontigs/ | sed -n '/\.subcontig$/p' | sed 's|^|'"$outdir"'/Subco
 ls "$outdir"/excludedSubcontigs/ | sed -n '/\.subcontig$/p' | sed 's|^|'"$outdir"'/excludedSubcontigs/|' | \
   xargs cat >> "$outdir"/BBindex/BBIndex.fasta
 bbmap.sh ref="$outdir"/BBindex/BBIndex.fasta path="$outdir"/BBindex deterministic=t averagepairdist=200
+
+# writing options that were used in PreProcessR for future reference when running StrainR
+touch "$outdir"/options.txt
+printf "indir\t%s\noutdir\t%s\nexcludesize\t%s\n" \
+  $indir $outdir $excludesize >> "$outdir"/options.txt
+
+if [ -z "$subcontigsize" ]; then
+  printf "subcontigsize\t%s\n" "N50" >> "$outdir"/options.txt
+else
+  printf "subcontigsize\t%s\n" "$subcontigsize" >> "$outdir"/options.txt
+fi
+
+printf "readsize\t%s\nkmersize\t%s\n" \
+  $readsize $ksize >> "$outdir"/options.txt
+
+if [[ $singleend == true ]]; then
+  printf "singleend\tTRUE\n" >> "$outdir"/options.txt
+else
+  printf "singleend\tFALSE\n" >> "$outdir"/options.txt
+fi
 
 echo "PreProcessR complete"
 echo "Total Run Time: $((($SECONDS - $START_TIME)/60)) min $((($SECONDS - $START_TIME)%60)) sec"  
diff --git a/src/StrainR b/src/StrainR
--- a/src/StrainR
+++ b/src/StrainR
@@ -36,9 +36,9 @@ for argument in $options
 StrainR normalizes mapping from reads using the output from PreProcessR\n\
 \tRequired Arguments:\n\
 \t\t-1/--forward path/to/forward.fastq.gz\t\t: path to forward reads\n\
-\t\t-2/--reverse path/to/reverse.fastq.gz\t\t: path to reverse reads\n\
 \t\t-r/--reference path/to/reference/directory\t: path to the output directory generated by PreProcessR\n\
 \tOptional Arguments:\n\
+\t\t-2/--reverse path/to/reverse.fastq.gz\t\t: path to reverse reads\n\
 \t\t-c/--weightedpercentile number\t: Weighted percentile for a strain's FUKMs to use in abundance estimation [Default = 60]\n\
 \t\t-s/--subcontigfilter number\t: Percentage of a strain's subcontigs that should be filtered out based on number of unique k-mers [Default = 0]\n\
 \t\t-b1/--background1 path/to/background1.fq.gz\t: path to forward background reads for exclusion. This is not necessary in a typical use case. [Default = None]\n\
@@ -53,74 +53,140 @@ StrainR normalizes mapping from reads using the output from PreProcessR\n\
     esac
   done
 
+if [ -z "$reference" ]; then
+  echo "Error: Reference directory needs to be provided with -r or --reference. Use 'StrainR --help' for more info."
+  exit
+fi
+if [ ! -d "$reference" ]; then
+  echo "Error: Reference directory doesn't exist."
+  exit
+fi
+if ! [ -f "$reference"/options.txt ]; then
+  echo "Error: Reference directory doesn't have options file. You may be using a reference generated by an old version of PreProcessR."
+  exit
+fi
+
+if [[ $(grep 'singleend' "$reference"/options.txt | sed 's/.*\t//') == "TRUE" ]]; then
+  singleends=true;
+else
+  singleends=false;
+fi
 if [ -z "$forward" ]; then
   echo "Error: Forward reads need to be provided with -1 or --forward. Use 'StrainR --help' for more info."
   exit
 fi
 if [ -z "$reverse" ]; then
-  echo "Error: Reverse reads need to be provided with -1 or --reverse. Use 'StrainR --help' for more info."
-  exit
-fi
-if [ -z "$reference" ]; then
-  echo "Error: Reference directory needs to be provided with -r or --reference. Use 'StrainR --help' for more info."
-  exit
+  echo "WARNING: You did not provide reverse reads with -2 or --reverse. StrainR2 will now be running in single end read mode Use 'StrainR --help' for more info."
+  if [[ $singleends == false ]]; then
+    echo "Error: PreProcessR was not run with single ends enabled. Please regenerate the reference directory using the --singleend option or provide paired end reads."
+    exit
+  fi
+else
+  if [[ $singleends == true ]]; then
+    echo "Error: PreProcessR was run with single ends enabled. Please regenerate the reference directory without using the --singleend option or provide single end reads."
+    exit
+  fi
 fi
 if [ -d "$outdir" ]; then
   echo "Error: Output directory already exists."
   exit
 fi
 
-
-mkdir "$outdir"
+if ! mkdir "$outdir"; then
+  echo "Error: failed to create outdir. Exiting."
+  exit
+fi
 mkdir "$outdir"/tmp
 
 #trim reads
 echo Trimming Reads
-fastp -i "$forward" -o "$outdir"/tmp/forward.fastq.gz \
-  -I "$reverse" -O "$outdir"/tmp/reverse.fastq.gz \
-  --trim_poly_g --json "$outdir" --html "$outdir" \
-  --length_required 50 --n_base_limit 0 \
-  --thread "$threads"
+if [[ $singleends == false ]]; then
+  fastp -i "$forward" -o "$outdir"/tmp/forward.fastq.gz \
+    -I "$reverse" -O "$outdir"/tmp/reverse.fastq.gz \
+    --trim_poly_g --json "$outdir" --html "$outdir" \
+    --length_required 50 --n_base_limit 0 \
+    --thread "$threads"
+else
+  fastp -i "$forward" -o "$outdir"/tmp/forward.fastq.gz \
+    --trim_poly_g --json "$outdir" --html "$outdir" \
+    --length_required 50 --n_base_limit 0 \
+    --thread "$threads"
+fi
 
 #map reads
 echo Mapping Reads
-bbmap.sh\
-  in="$outdir"/tmp/forward.fastq.gz in2="$outdir"/tmp/reverse.fastq.gz \
-  ref="$reference"/BBindex/BBIndex.fasta \
-  outm="$outdir"/"$prefix".sam \
-  rpkm="$outdir"/"$prefix".rpkm \
-  threads="$threads" deterministic=t averagepairdist=200 \
-  -Xmx"$mem"g \
-  perfectmode=t local=f ambiguous=toss pairedonly=t nodisk=t
+if [[ $singleends == false ]]; then
+  bbmap.sh\
+    in="$outdir"/tmp/forward.fastq.gz in2="$outdir"/tmp/reverse.fastq.gz \
+    ref="$reference"/BBindex/BBIndex.fasta \
+    outm="$outdir"/"$prefix".sam \
+    rpkm="$outdir"/"$prefix".rpkm \
+    threads="$threads" deterministic=t averagepairdist=200 \
+    -Xmx"$mem"g \
+    perfectmode=t local=f ambiguous=toss pairedonly=t nodisk=t
+else
+  bbmap.sh\
+    in="$outdir"/tmp/forward.fastq.gz \
+    ref="$reference"/BBindex/BBIndex.fasta \
+    outm="$outdir"/"$prefix".sam \
+    rpkm="$outdir"/"$prefix".rpkm \
+    threads="$threads" deterministic=t \
+    -Xmx"$mem"g \
+    perfectmode=t local=f ambiguous=toss nodisk=t
+fi
 
 samtools view --threads "$threads" -bS "$outdir"/"$prefix".sam | \
 samtools sort --threads "$threads" -o "$outdir"/"$prefix".bam
 
 # background subtraction if background provided
-if [ ! -z "$background1" ] && [ ! -z "$background2" ]; then
+if [ ! -z "$background1" ]; then
+  background_single = true
+  if [ ! -z "$background2" ]; then
+    background_single = false
+  fi
   #trim background reads
   echo Trimming Background Reads
-  fastp -i "$background1" -o "$outdir"/tmp/bg_forward.fastq.gz \
-    -I "$background2" -O "$outdir"/tmp/bg_reverse.fastq.gz \
-    --trim_poly_g --json "$outdir" --html "$outdir" \
-    --length_required 50 --n_base_limit 0 \
-    --thread "$threads"
+  if [[ $background_single == false ]]; then
+    fastp -i "$background1" -o "$outdir"/tmp/bg_forward.fastq.gz \
+      -I "$background2" -O "$outdir"/tmp/bg_reverse.fastq.gz \
+      --trim_poly_g --json "$outdir" --html "$outdir" \
+      --length_required 50 --n_base_limit 0 \
+      --thread "$threads"
+  else
+    fastp -i "$background1" -o "$outdir"/tmp/bg_forward.fastq.gz \
+      --trim_poly_g --json "$outdir" --html "$outdir" \
+      --length_required 50 --n_base_limit 0 \
+      --thread "$threads"
+  fi
 
   #map background reads
   echo Mapping Background Reads
-  bbmap.sh\
-    in="$outdir"/tmp/bg_forward.fastq.gz in2="$outdir"/tmp/bg_reverse.fastq.gz \
-    ref="$reference"/BBindex/BBIndex.fasta \
-    outm="$outdir"/"$prefix"_bg.sam \
-    rpkm="$outdir"/"$prefix"_bg.rpkm \
-    threads="$threads" deterministic=t averagepairdist=200 \
-    -Xmx"$mem"g \
-    perfectmode=t local=f ambiguous=toss pairedonly=t nodisk=t
-  
+  if [[ $background_single == false ]]; then
+    bbmap.sh\
+      in="$outdir"/tmp/bg_forward.fastq.gz in2="$outdir"/tmp/bg_reverse.fastq.gz \
+      ref="$reference"/BBindex/BBIndex.fasta \
+      outm="$outdir"/"$prefix"_bg.sam \
+      rpkm="$outdir"/"$prefix"_bg.rpkm \
+      threads="$threads" deterministic=t averagepairdist=200 \
+      -Xmx"$mem"g \
+      perfectmode=t local=f ambiguous=toss pairedonly=t nodisk=t
+  else
+    bbmap.sh\
+      in="$outdir"/tmp/bg_forward.fastq.gz \
+      ref="$reference"/BBindex/BBIndex.fasta \
+      outm="$outdir"/"$prefix"_bg.sam \
+      rpkm="$outdir"/"$prefix"_bg.rpkm \
+      threads="$threads" deterministic=t \
+      -Xmx"$mem"g \
+      perfectmode=t local=f ambiguous=toss nodisk=t
+  fi
+
   rm "$outdir"/"$prefix"_bg.rpkm
 
   samtools view --threads "$threads" -bS "$outdir"/"$prefix"_bg.sam | \
   samtools sort --threads "$threads" -o "$outdir"/"$prefix"_bg.bam
+
+  rm "$outdir"/"$prefix"_bg.sam
 
   echo Filtering Background Reads from Sample Reads
   samtools view -H "$outdir"/"$prefix".bam | grep '^@SQ' | sed -E 's/@SQ\tSN://;s/\tLN:/\t/' > "$outdir"/genome_file.txt
@@ -134,26 +200,43 @@ if [ ! -z "$background1" ] && [ ! -z "$background2" ]; then
   samtools sort --threads "$threads" -n "$outdir"/"$prefix"_filtered.bam \
     -o "$outdir"/"$prefix"_filtered_sorted.bam
   
-  rm "$prefix"_filtered.bam
+  rm "$outdir"/"$prefix"_filtered.bam
+  
+  if [[ $singleends == false ]]; then
+    samtools fastq -1 "$outdir"/"$prefix"_filtered_1.fq \
+      -2 "$outdir"/"$prefix"_filtered_2.fq \
+      -0 /dev/null -s /dev/null -n --threads "$threads" \
+      "$outdir"/"$prefix"_filtered_sorted.bam
+  else
+    samtools fastq -1 "$outdir"/"$prefix"_filtered_1.fq \
+      -0 /dev/null -s /dev/null -n --threads "$threads" \
+      "$outdir"/"$prefix"_filtered_sorted.bam
+  fi
 
-  samtools fastq -1 "$outdir"/"$prefix"_filtered_1.fq \
-    -2 "$outdir"/"$prefix"_filtered_2.fq \
-    -0 /dev/null -s /dev/null -n --threads "$threads" \
-    "$outdir"/"$prefix"_filtered_sorted.bam
-
-  bbmap.sh \
-    in="$outdir"/"$prefix"_filtered_1.fq \
-    in2="$outdir"/"$prefix"_filtered_2.fq \
-    ref="$reference"/BBindex/BBIndex.fasta \
-    outm="$outdir"/filtered_"$prefix"_remap.sam \
-    rpkm="$outdir"/filtered_"$prefix"_remap.rpkm \
-    threads="$threads" deterministic=t averagepairdist=200 \
-    -Xmx"$mem"g perfectmode=t local=f ambiguous=toss pairedonly=t nodisk=t
+  if [[ $singleends == false ]]; then
+    bbmap.sh \
+      in="$outdir"/"$prefix"_filtered_1.fq \
+      in2="$outdir"/"$prefix"_filtered_2.fq \
+      ref="$reference"/BBindex/BBIndex.fasta \
+      outm="$outdir"/filtered_"$prefix"_remap.sam \
+      rpkm="$outdir"/filtered_"$prefix"_remap.rpkm \
+      threads="$threads" deterministic=t averagepairdist=200 \
+      -Xmx"$mem"g perfectmode=t local=f ambiguous=toss pairedonly=t nodisk=t
+  else
+    bbmap.sh \
+      in="$outdir"/"$prefix"_filtered_1.fq \
+      ref="$reference"/BBindex/BBIndex.fasta \
+      outm="$outdir"/filtered_"$prefix"_remap.sam \
+      rpkm="$outdir"/filtered_"$prefix"_remap.rpkm \
+      threads="$threads" deterministic=t \
+      -Xmx"$mem"g perfectmode=t local=f ambiguous=toss nodisk=t
+  fi
 
   rm "$outdir"/"$prefix"_filtered_1.fq
   rm "$outdir"/"$prefix"_filtered_2.fq
   rm "$outdir"/"$prefix"_filtered_sorted.bam
   rm "$outdir"/filtered_"$prefix"_remap.sam
+  rm "$outdir"/genome_file.txt
 fi
 
 rm "$outdir"/"$prefix".sam
